version: '3.8'

services:
    backend:
        image: nhhnam/shopee-backend:latest # Dùng image từ Docker Hub
        container_name: shopee-backend
        ports:
            - 5000:5000 # Mở cổng 5000 cho backend
        environment:
            - DB_HOST=db
            - DB_PORT=1433
            - DB_USER=sa
            - DB_PASSWORD=YourStrongP@ssword123
            - DB_NAME=shopee
        depends_on:
            - db
        restart: always # Tự khởi động lại nếu container bị crash

    db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: sql-server
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=YourStrongP@ssword123
            - MSSQL_PID=Express
        ports:
            - 1433:1433
        volumes:
            - sqlserver-data:/var/opt/mssql
        restart: always # Đảm bảo DB cũng tự khởi động lại

volumes:
    sqlserver-data:
        driver: local
